name: Security Scan (SAST)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  semgrep-scan:
    name: Run Semgrep Security Scanner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Semgrep Security Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"